### PR TITLE
travis support

### PR DESCRIPTION
**Pull request by ioggstream**
Travis build ok for all the intended tests.

No code changes.

### CODE REVIEW

**Comment by secynic** [comment]
Please remove simplejson from both requirements files, and dnspython3 from the python2.txt. I will merge and test Travis once you do that. Thanks.

**Comment by ioggstream** [comment]
Done ;)

Thx++

**Comment by secynic** [comment]
I still see dnspython3 in python2.txt.

**Comment by secynic** [comment]
Thanks!

**Pull request merged**
